# Generated by Django 6.0.1 on 2026-02-05 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('is_published', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_event', 'Can create event'), ('can_edit_own_event', 'Can edit own event')],
                'indexes': [models.Index(fields=['date'], name='events_even_date_5e8e1c_idx')],
            },
        ),
    ]
