# Generated by Django 6.0.1 on 2026-01-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_date_event_online_link_alter_event_poster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_create_event', 'Can create event'), ('can_edit_own_event', 'Can edit own event')]},
        ),
    ]
