# Generated by Django 6.0.1 on 2026-02-05 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('early_bird', 'Early Bird')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'ordering': ['event', 'type'],
                'unique_together': {('event', 'type')},
            },
        ),
        migrations.CreateModel(
            name='IssuedTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='ticket_qr/')),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='orders.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='tickets.ticket')),
            ],
            options={
                'permissions': [('can_scan_tickets', 'Can scan tickets')],
            },
        ),
    ]
