# Generated by Django 6.0.1 on 2026-01-20 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_transaction_external_response_and_more'),
        ('tickets', '0003_ticket_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
        migrations.CreateModel(
            name='IssuedTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='ticket_qr/')),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='orders.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='tickets.ticket')),
            ],
        ),
    ]
