# Generated by Django 6.0.1 on 2026-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_qr_code_issuedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('early_bird', 'Early Bird')], max_length=10),
        ),
    ]
