# Generated by Django 6.0.1 on 2026-01-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuedticket',
            options={'permissions': [('can_scan_tickets', 'Can scan tickets')]},
        ),
    ]
