# Generated by Django 6.0.1 on 2026-01-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_issue_refunds', 'Can issue refunds')]},
        ),
    ]
